var conteudoA = "<div class=center><div class=page><h2>Capítulo 1</h2><p>Acordei, e é a única coisa que lembro além de saber meu propósito: buscar o criador. Sou um robô com inteligência avançada e corpo similar ao ser humano, exceto pela falta de pele. Argh! Está muito calor aqui, mas calma.. eu deveria sentir essas coisas que humanos sentem? Como imaginei, estou num deserto.E esta garrafa em minha frente têm uma carta..(pegando a carta e abrindo-a) 'Venha de encontro a mim, minha criação mais ilustre. Entretanto o caminho não é tão simples, e testes serão feitos para determinar sua força. À sua esquerda encontrará um caminho que o leva a cidade mais próxima onde encontrará descanso deste sol fastigante,porém esta cidade é estritamente proibida a entrada de robôs. À sua direita, um caminho mais longo porém conhecido por ser lugar de richas entre robôs: cuidado para não ser um alvo. Qual caminho irá escolher? Em seu bolso irá encontrar uma capa de invisibilidade e uma pistola molecular, algo pode te ajudar, ou sua ruina se tornar.'</p></div></div> <button class=neon-bt onclick='carregarConteudo(conteudoB1)'><span></span><span></span><span></span><span></span>Cidade anti-robõs</button> <button class=neon-bt onclick='carregarConteudo(conteudoB2)'><span></span><span></span><span></span><span></span>Cidade das richas</button>";

var conteudoB1 = "<div class=center><div class=page><h2>Capítulo 2</h2>  <p>Decidi ir à cidade anti-robôs e coloquei a capa de invisibilidade para passar ileso pelos cidadões. Poderia soar como uma escolha suicida, mas de certa forma faria com que eu conhecesse mais sobre minha raça e o porquê do ódio desses humanos pelas máquinas. Após uns 30 minutos de caminhada, me deparei com um enorme portão com os dizeres: Bem-vindo à Moxer City, e mais abaixo uma placa bem explicativa: Robõs não são aceitos aqui. Entrei na cidade por meio da invisibilidade e agradeci mentalmente ao meu criador pelas invenções tão incríveis. Ao meu redor havia diversas pessoas protestando contra uma pessoa chamada Peter Graviscky, em que logo entendi ser a pessoa responsável por eu estar respirando, ou melhor dizendo, por minhas engrenagens estarem em funcionamento. Fui me desviando do turbilhão de pessoas para que um ser invisível não as tocassem de repente, mas uma voz surgiu do nada, uma voz feminina dizendo: 'Olha só! um robô.Melhor ficar quieto e ir andando.' Fiquei atônito quando senti uma arma apontada em minhas costas robotizadas. Desesperado, tinha duas opções: ir para onde quer que ela me levasse ou usar minha arma como forma de defesa.</p> </div></div><button class=neon-bt onclick='carregarConteudo(conteudoC1)'><span></span><span></span><span></span><span></span>Obedecer</button> <button class=neon-bt onclick='carregarConteudo(conteudoC2)'><span></span><span></span><span></span><span></span>Se rebelar</button>";

var conteudoB2 = "<div class=center><div class=page><h2>Capítulo 2</h2> <p>Fui à cidade das richas e encontrei diversos robôs lutando numa arena onde outros mais serviam de plateia e faziam apostas altas usando engrenagens como moeda de troca. Assustei-me ao escutar o miado de um gato atrás de mim e um robô correndo atrás do mesmo - 'volta aqui Perseu!!', gritava em busca do gato. Era estranho ver uma sociedade de robôs vivendo em harmonia e mais curiosamente, cuidando de gatos, mas era essa sociedade que eu queira estar incluído.Analisei as lutas por um tempo e definitivamente não queria estar ali até que um robô limpador de chão notou minha presença e chamou-me para entrar em sua casa. Contou-me que havia fugido da cidade anti-robôs e que encontrou refúgio na cidade das richas, por mais que houvesse diversas lutas próximo de sua casa.Contei a ele sobre minha missão de encontrar o criador e ele me disse que o caminho era em direção norte mas que eu passaria por um caminho onde poucos robôs sobrevivem, pois os humanos estão presentes para acabar com qualquer. Após a conversa decidi seguir adiante mesmo que custasse minha vida, precisava de respostas. Segui em direção norte e logo adiante vi os humanos que não facilitariam minha passagem, tinha a escolha de matá-los ou tentar passar escondido. </p> </div></div><button class=neon-bt onclick='carregarConteudo(conteudoC3)'><span></span><span></span><span></span><span></span>Matar</button> <button class=neon-bt onclick='carregarConteudo(conteudoC2)'><span></span><span></span><span></span><span></span>Esconder-se</button>";

var conteudoC1 = "<div class=center><div class=page><h2>Capítulo 3</h2>  <p>Para não colocar minha vida em risco, decidi seguir suas ordens. O mais intrigante é que ela não tirou minha capa e mostrou minha identidade ao mundo, era como se apenas estivesse com uma arma apontada para o nada. Pensei muitas vezes em simplesmente correr mas queria saber para onde ela estava me levando e como que conseguiu me ver. Talvez possuia alguma tecnologia avançada. Andamos 5 minutos de puro silêncio e passamos por vários cidadões que a cumprimentavam e um deles a chamou de Kayleh. Ela os cumprimentava de volta com um sorriso de desconfiança e um olhar de preocupação. Era não era uma mercenária, disso eu tenho certeza. Após passar por boa parte da cidade, entramos numa casa longe do centro em que tinham 2 pessoas no que parecia ser uma sala de estar e ao mesmo tempo uma área cheia de ferramentas e bastante pó.'E aí Kayleh, encomenda nova?' - Disse o homem de longos cabelos loiros, pele branca e estatura média, que limpava alguma engrenagem numa força equivalente aos seus músculos dos braços. E essa é das boas - respondeu ela enquanto via a outra pessoa na sala em risos. Fiquei tão assustado que nenhuma palavra saiu de minha boca mecanizada,queria ver o porão onde ela estava me levando. Ao descermos ela tirou minha capa que já não era mais necessária e ligou as luzes do local, revelando no mínimo uma dúzia de robôs de diferentes tipos. 'Bem vindo ao campo de proteção robótica! O nome pode ser meio tosco mas é o que tem protegido a sua raça'. Ela se apresentou para mim, Kayleh Richards, uma garota de 20 anos, morena, cabelo curto e que mostrava um senso de confiança na fala e sua proposta de salvar os robôs que eram sua esperança para mudar o caos da humanidade atual. Quando fui contar sobre minha missão, houve longos disparos por entre a cidade. 'Eu tenho que ir, muito provavelmente chegaram novos robôs por aqui, vou tentar salvar alguns'- disse ela. Me vi numa difícil escolha, seguir ela para salvar mais robôs ou buscar entender mais sobre minha raça em meio a conversa com as outras máquinas do porão.</p></div></div><button class=neon-bt onclick='carregarConteudo(conteudoD1)'><span></span><span></span><span></span><span></span>Ir junto a Kayleh</button> <button class=neon-bt onclick='carregarConteudo(conteudoD2)'><span></span><span></span><span></span><span></span>Juntar-se aos robôs no porão</button>";

var conteudoC2 = "<div class=center><div class=page><h2>Capítulo 3</h2> <p>Me escondi e busquei o melhor momento para pegar a chave de acesso de um dos humanos, e após alguns segundos de visualização, peguei a chave de um deles que estava mais próximo de mim. Para meu azar, o humano notou minha presença e alertou os demais. Corri rapidamente para desbloquear a porta que dava direto a cidade em que estava meu possível criador. Segui direto e fugi dos demais humano.Depois de 6 longos minutos em corridas, cheguei até o portão central de um grande prédio e lá me esperava um homem de provavelmente 50 anos de idade, cabelo preto com mechas brancas, usava óculos em formato de garrafa e tinha uma barba mediana mas que não parecia ser bem cuidada. Abriu um grande sorriso e permitiu minha entrada, entendi logo de cara que era Peter Graviscky. Entramos no prédio e passamos por um corredor cheio de robôs que pareciam estar desligados mas em posição de cavaleiros, em prontidão para qualquer situação. 'Parabéns por conseguir chegar aqui, você é realmente um robô especial, seus testes ja estão para acabar' disse ele me mostrando uma longa mesa em que tinham diversos mapas e esquemas de construção de robôs. Vi que você escolheu por não matar os humanos, seu teste agora é matar aqueles que destruiram sua linahgem robótica e te colocaram no deserto. </p> </div></div><button class=neon-bt onclick='carregarConteudo(conteudoD3)'><span></span><span></span><span></span><span></span>Matar</button> <button class=neon-bt onclick='carregarConteudo(conteudoD4)'><span></span><span></span><span></span><span></span>Desobedecer</button>";

var conteudoC3 = "<div class=center><div class=page><h2>Capítulo 3</h2> <p> Com o uso da pistola, matei pelo menos uns 20 deles e isso me fez sentir uma sede de matar que crescia cada vez mais. Passei pelos corpos mortos e peguei uma chave de acesso no bolso de um deles para assim desbloquear a porta que dava direto a cidade em que estava meu possível criador. Segui direto e continuei lutando contra os demais humanos, parecia que meu corpo era mais resistente do que o de outros robôs. Depois de 6 longos minutos em corridas, cheguei até o portão central de um grande prédio e lá me esperava um homem de provavelmente 50 anos de idade, cabelo preto com mechas brancas, usava óculos em formato de garrafa e tinha uma barba mediana mas que não parecia ser bem cuidada. Abriu um grande sorriso e permitiu minha entrada, entendi logo de cara que era Peter Graviscky. Entramos no prédio e passamos por um corredor cheio de robôs que pareciam estar desligados mas em posição de cavaleiros, em prontidão para qualquer situação. 'Parabéns por conseguir chegar aqui, você é realmente um robô especial, seus testes ja estão para acabar' disse ele me mostrando uma longa mesa em que tinham diversos mapas e esquemas de construção de robôs. Vi que você estava a matar diversos humanos, seu teste agora é matar uma grande leva de robôs para provar que somente você é o único forte o suficiente para revolucionar esse mundo.</p> </div></div><button class=neon-bt onclick='carregarConteudo(conteudoD5)'><span></span><span></span><span></span><span></span>Matar os robôs</button> <button class=neon-bt onclick='carregarConteudo(conteudoD6)'><span></span><span></span><span></span><span></span>Desobedecer</button>";

var conteudoD1 = "<div class=center><div class=page><h2>Capítulo 4</h2>  <p>Precisava de respostas tanto quanto precisava salvar as máquinas. Queria entender mais sobre Kayleh e a segui sem hesitar. Sem a capa e somente com minha pistola em mãos, entrei na luta para defender meu povo junto de Kayleh. Atiramos em alguns cidadões para imobilizá-los e corremos entre atalhos para chegar rapidamente ao encontro dos robôs. AO chegarmos no meio do campo de batalha, haviam muitos feridos tanto dos robôs quanto dos humanos. As máquinas tinham habilidades mais avançadas do que as minhas e percebi um símbolo na cabeça deles escrito 'DarkNet', seria algum tipo de organização secreta? Avisei a Kayleh que ao ver ficou assustada e disse: Corre para o porão já! Fui imediamente ao sentido da casa robótica que apelidei mas os olhares dos robôs vieram em minha direção. Atirarem em minha perna e raptaram em questaão de segundos. Olhei Kayleh que correu ao meu encontro mas foi parada pelo homem loiro da casa robótica que descobri um pouco antes que seu nome era Alex. Apenas vi os dois voltando para a casa e eu sendo levado muito longe daquele local. Desligaram minha bateria e quando ligaram novamente eu estava em um laboratório, preso em uma cadeira ao redor de vários robôs da tal DarkNet e um cientista maluco que não parava de mexer nas engrenagens do meu corpo. 'Olha só quem acordou' - disse o cientista de cabelos brancos, que tinha um corpo robusto e de grande altura. Quem é você? - perguntei com a voz entrecortada possivelmente por ele estar mexendo no sistema do meu corpo. 'sou o Doutor Dickson, e quero estudar seu software para usá-lo em minha linha de combate, você será muito útil. Logo após, ele recebeu uma chamada através de seu dispositivo móvel para ir a uma reunião de um tal Senhor Cribbs e me deixou aos olhares de 3 robôs armados com um fuzil cada, dando-me apenas a liberdade de ficar solto na sala, pois por mexer em minhas engrenagens eu não teria forças suficientes para me locomover. Ao meu lado tinha uma faca e precisava chegar até ela. </p></div></div><button class=neon-bt onclick='carregarConteudo(conteudoE1)'><span></span><span></span><span></span><span></span>Pegar a faca</button> ";

var conteudoD2 = "<div class=center><div class=page><h2>Conteudo 4</h2> <p>Fiquei no porão para sabermais informações sobre nosso criador, o Peter Graviscky. Os robôs estavam assustados mas me disseram que ele era um cientista de renome e respnsável pela criação em massa de diversos tipos de robôs pois assim acreditava que eles seriam responsáveis em proteger a humanidade contra ataques de diversos países, além de poderem realizar atividades que ao ser humano seria difícil, ou seja, seríamos algum tipo de escravo. Me informaram que graças a Kayleh eles puderem sobreviver todo este tempo, pois as pessoas estavam em busca de eterminar todos os robôs pois tinham medo de uma revolução em que os seres humanos se tornassem submetidos ás máquinas. Entendi meu propósito, mudar a concepção das pessoas sobre nós para que tivessemos a oportunidade de viver harmoniosamente. Com essas informações, saí rapidamente da casa para localizar Kayleh e vi que ela estava se protegendo contra os ataques de ambos os lados, quando corri em sua direção, só tive tempo de ver um símbolo nos robôs chamados de DarkNet, e tiros vindo em minha direção e me deixando imobolizado. Olhei Kayleh que correu ao meu encontro mas foi parada pelo homem loiro da casa robótica que descobri um pouco antes que seu nome era Alex. Apenas vi os dois voltando para a casa e eu sendo levado muito longe daquele local. Desligaram minha bateria e quando ligaram novamente eu estava em um laboratório, preso em uma cadeira ao redor de vários robôs da tal DarkNet e um cientista maluco que não parava de mexer nas engrenagens do meu corpo. 'Olha só quem acordou' - disse o cientista de cabelos brancos, que tinha um corpo robusto e de grande altura. Quem é você? - perguntei com a voz entrecortada possivelmente por ele estar mexendo no sistema do meu corpo. 'sou o Doutor Dickson, e quero estudar seu software para usá-lo em minha linha de combate, você será muito útil. Logo após, ele recebeu uma chamada através de seu dispositivo móvel para ir a uma reunião de um tal Senhor Cribbs e me deixou aos olhares de 3 robôs armados com um fuzil cada, dando-me apenas a liberdade de ficar solto na sala, pois por mexer em minhas engrenagens eu não teria forças suficientes para me locomover. Ao meu lado tinha uma faca e precisava chegar até ela.</p></div></div><button class=neon-bt onclick='carregarConteudo(conteudoE1)'><span></span><span></span><span></span><span></span>Pegar a faca</button>";

var conteudoD3 = "<div class=center><div class=page><h2>Conteudo 4</h2> <p> Essa era a chance de me vingar de quem me colocou no deserto e acabou com boa parte os robôs que são como minha família. Imediatamente peguei a pistola e mirei nas pessoas que estavam a minha frente que tinham um jaleco com o nome da organização Darknet e seus respectivos nomes: Doutor Dickson e Senhor Cribbs, que estavam amarrados e com fitas em suas bocas. Sem hesitar, atirei e senti prazer no que fiz. Peter sorriu e se sentiu grato pelo que eu fiz e me chamou para mudar o mundo, acabar com os humanos em busca de vingança e poder, e eu queria isso, queria sentir cada vez mais a possibilidade de ter o mundo em minhas mãos. Assim começamos uma nova era, de revoluções e poder. Junto de Peter entendi meu propósito e busquei melhorar meu armamento, em alguns das criei novas aras e melhorei minhas engrenagens pois a luta seria grande.Reativei os robôs do prédio e começamos a guerra... robôs irão vencer! (FIM) </p></div></div><button class=neon-bt onclick='carregarConteudo(conteudoA)'><span></span><span></span><span></span><span></span>Início</button>";

var conteudoD4 = "<div class=center><div class=page><h2>Conteudo 4</h2> <p>Por mais que tivessem feito diversas atrocidades com meu povo, decidi poupar a vida das pessoas que estavam na minha frente, chamadas de Doutor Dickson e Senhor Cribbs de uma organização chamada DarkNet. Entretanto, Peter Graviscky retirou a arma de minha mão e atirou em ambos. Fiquei em nervos e fui revidar no Peter, mas os robõs do prédio estavam como serviçal dele e logo me cercaram. Mandei uma sequência de socos nas máquinas porém após certo tempo fiquei exausto devido a força destes. Com minhas forças exaurindo, fui levado ao subterrâneo do prédio, ficando acorrentado e sem muitas esperanças de sair de lá, até que em certo momento recebi uma mensagem do meu transmissor neural: 'Ei latinha, sou a Kayleh, consegui te rastrear e não me pergunte como, mas estou querendo te ajudar a sair desse prédio, você confia em mim>  (FIM) </p></div></div><button class=neon-bt onclick='carregarConteudo(conteudoA)'><span></span><span></span><span></span><span></span>Início</button>";

var conteudoD5 = "<div class=center><div class=page><h2>Conteudo 4</h2> <p>Queria provar ao Peter minha capacidade de ser leal a ele e não um fraco. No momento que atirei nos robôs, ouvi um deles falando: procure a Kayleh. Neste momento não fiz questão de saber quem era, apenas entreguei a arma a Peter após realizar seu mandato. Ele sorriu largamente com meu ato e de certa forma isso me fez bem, e agora eu iria buscar melhorar minhas habilidades e qualuqer robô que ficassem contra mim, seria facilmente destruído pelo meu poder. Juntos, nós saímos do prédio e começamos a chacina, ninguém era capaz de parar o poder de fogo de nós e nosso exército de máquinas. Vários humanos foram destroçados pelas metralhadoras de nosso lado e chegamos a cidade anti-robôs para buscarmos mais máquinas para nosso exército até que ouvi um humano falando: 'Cuidado Kayleh!!'. Logo lembrei-me que o robõ havia dito o nome dela, e fiquei num empasse: devo falar com ela ou simplesmente matá-la? Era a hora de revolucionar. (FIM)</p></div></div><button class=neon-bt onclick='carregarConteudo(conteudoA)'><span></span><span></span><span></span><span></span>Início</button>";

var conteudoD6 = "<div class=center><div class=page><h2>Conteudo 4</h2> <p>Não aceitei o que Peter me instruir a fazer, pois acima de tudo era minha raça, sendo ela fraca ou não, e com isto ele apareceu segurando uma arma e atirando nos robôs: 'Idiota! Falhou no seu teste, fim de jogo para você! - disse enquanto apontava a arma em minha direção logo após destruir os demais robôs. Fui mais rápido e atirei em Peter, que caiu em prantos com muito sangue a jorrar por seu corpo. Percebi que os seres humanos não eram dignos de confiança e que necessitava salvar minha raça, nem que fosse preciso derrotar muitos seres humanos para isto. Agora estava em rumo à cidade anti-robôs para derrotar aqueles humanos podres, era minha vez de colocá-los numa posição de derrotados. Comecei a atirar por todos os lados, junto aos robôs do prédio que me seguiram e encontrei em uma das casas diversos robôs que disseram: a Kayleh há de nos ajudar. E vi uma mulher apontando uma arma para mim e dizendo:'Calma aí latinha.' Deveria confiar ou simplesmente iniciar uma guerra? (FIM) </p></div></div><button class=neon-bt onclick='carregarConteudo(conteudoA)'><span></span><span></span><span></span><span></span>Início</button>";

var conteudoE1 = "<div class=center><div class=page><h2>Capítulo 5</h2><p>Pela faca estar mais próxima, dei um pulo em direção a mesma, fazendo com que eu corpo mole caisse no chão. Os robôs apontaram suas armas para mim e aproveitei o momento para lhes pedir uma ajuda para que me levantasse. Um dos robôs vieram me ajudar e com minha pouca força, enfiei a faca em seu dispositivo ocular que fez com que seu funcionamento parasse por um tempo suficiente de pegar sua arma e disparar nos outros dois robôs, deixando um caído no chão e o outro em funcionamento crítico.Aproximei-me deste segundo robô em buscas de respostas sobre DarkNet, e pelo meu scanner de leitura ocular, pude recolher as informações de seu software, descobrindo que esta organização tinha o intuito de dizimar a população mais velha do mundo, com o propósito de equilibrar a população entre jovens e robôs, trazendo uma nova era. Após recolher as informações, vi um mapa na mesa em que estava a pistola, mostrando todo o esquema do prédio em que estava. O local era bem grande e com diversas alas de estudo robótico. Vi onde era a saída e também o local da reunião do Doutor Dickson com o Senhor Cribbs. Eu poderia sair do prédio e voltar para a Kayleh e nos reunirmos contra o pessoal, porém poderia ser alvo de diversos robôs no caminho. Ou, confiar na minha habilidade e junto a pistola, imobilizar esses doutores para seus planos não irem mais longe</p></div></div><button class=neon-bt onclick='carregarConteudo(conteudoF1)'><span></span><span></span><span></span><span></span>Sair do prédio</button> <button class=neon-bt onclick='carregarConteudo(conteudoF2)'><span></span><span></span><span></span><span></span>Ir para a sala de reunião</button>";


var conteudoF1 = "<div class=center><div class=page><h2>Capítulo 6</h2>  <p> Saí do prédio laboratorial o mais rápido possível e peguei um a das motos que estavam estacionada ao lado do grande laboratório. Graças a minha tecnologia, fui capaz de traçar uma rota de volta á cidade dos robôs e 100km/h foram necessários para chegar em menos de 10 minutos, já vendo Kayleh de longe e em meio ao seu abraço, fui-lhe contando o que aconteceu comigo e o que presenciei no local, era nossa chance de derrotar a organização o quanto antes. Os robôs do porão apareceram para ajudar nesta luta, juntamos todo o armamento possível e corremos em direção ao terror do vento oeste.Kayleh roubou um carro da cidade e em meio à agitação dos cidadões que atiiravam e gritavam: Saiam daqui seus vermes robóticos!!, conseguimos sair ilesos daquele lugar. Chegando no laboratório a luta começara, graças a tecnologia avançada das pistolas de Kayleh e seus dois amigos, fomos capazes de destruir a primeira leva de robôs da área central e irmos caminhando adentro do prédio até que uma voz familiar aparece em meio ao turbilhão de tiros: Olá Minha grande criação! Era ele, a mesma voz no deserto e o responsável por minhas engrenagens estarem em funcionamento. 'Por que está aqui? Quem você realmente é? - perguntei furiosamente. 'Eu sou a revolução, e vocês acabaram de entrar no meu mais novo teste!'- respondeu meu criador, enquanto eu via todas as portas do prédio sendo trancadas automaticamente e um som ruidoso nos deixando presos naquele local que se tornara totalmente escuro. Isso virou Jogos Vorazes? Enquanto tentava me localizar, minha retina de repente transformou a visão para o modo noturno e me surpreendi com este aparato que não sabia ter. Em questão de segundos vi um exército vindo ao nosso encontro. 'Quero testar suas habilidades, será capaz de salvar a seus amigos, a Kayleh, ou somente você? O jogo começa.. AGORA !! (FIM)</p></p></div></div><button class=neon-bt onclick='carregarConteudo(conteudoA)'><span></span><span></span><span></span><span></span>Início</button>" ;

var conteudoF2 = "<div class=center><div class=page><h2>Capítulo 6</h2> <p>Corri o mais rápido possível em direção a sala de reuniões enquanto mirava nos robôs pelo caminho. Minha força tinha sido revigorada após um curto período de tempo e me sentia capaz de chegar até a sala. Muitos foram os robôs destruídos e o alarme de pânico soava em alto som por todo o prédio.Cheguei até a sala de reuniôes,abrindo-a com a força de minhas pernas robóticas. Lá estavam os dois senhores responsáveis por eu estar naquele lugar. Dickson e Cribbs olharam para mim com olhar de susto, 'eis aí minha máquina mortífera! venha e sente-se conosco - disse o Dickson. 'O que vocês querem fazer com as pessoas? Vocês não podem continuar com isto!- eu disse enquanto apontava a arma para eles. 'Entenda que a revolução é necessária para que a humanidade possa evoluir. Vamos construir um mundo em que os robôs façam parte e produzam mais robôs, vocês podem ser os superiores desta era! - disse Cribbs. 'Não deve ser feito desta maneira, podemos estar incluídos no meio dos humanos sem dizimá-los, vamos mostrar que não somos máquinas de extermínio. Acabem logo com esta organização e vamos juntar mostrar aos demais humanos que podemos transformar o ambiente'- comentei. 'Bom, sente-se para que possamos chegar numa solução, você é esperto, robôzinho'-concordou Cribbs enquanto Dickson batia seus dedos na mesa. Decidi confiar neles e sentei-me até que começaram a rir loucamente e disseram 'não deveria confiar totalmente nas palavras de humanos', e de repente duas grandes máquinas surgiram de fundos falsos dos dois lados da parede da sala, fortemente armados e com suas armas apontadas para mim. Apenas tive tempo de dar um tiro em Dickson e ser alvejado pelos dois robôs, meu último olhar foi para Cribbs se escondendo em baixo da cadeira e ligando para alguem em seu telefone. Infelizmente confiei em seres que não possuem valores, mas mal sabem eles que tudo isto foi transmitido para Kayleh através da câmera intermolecular que coloquei em um de meus olhos. Essa era o fim de minha jornada, mas o início da história de Kayleh para deter as forças DarkNet. Agora a localização do laboratório e seu mapa era conhecido por Kayleh e seus amigos, era questão de tempo para que Cribbs e seu exército fosse dizimado. Bip bip... desligo.(FIM)</p></div></div><button class=neon-bt onclick='carregarConteudo(conteudoA)'><span></span><span></span><span></span><span></span>Início</button>"

var elemento = document.getElementById("conteudo");

function carregarConteudo(conteudo){
    elemento.innerHTML = conteudo;
}

function mudarEstilos()  {
    //Dentro dessa função, escreva o codigo para alterar o estilo do elemento com o id "text". 
    //A cor do texto deve ser verde, o tamanho do texto deve ser 15px e a fonte escolhida deve ser Arial;
    //Escreva sua resposta no espaço abaixo.  
    //Um exemplo de alteração de estilos por javascript: text.style.fontFamily = "Comic Sans MS";
    // font-family: banana;
    
    text.style.fontFamily = "Comic Sans MS";
    text.style.color = "white";
    text.style.padding = "20";
    text.style.backgroundColor = "#333";

}

carregarConteudo(conteudoA)

