var conteudoA = "<div class=center><div class=page><h2>Conteudo A</h2><p>Acordei, e é a única coisa que lembro além de saber meu propósito: buscar o criador. Sou um robô com inteligência avançada e corpo similar ao ser humano, exceto pela falta de pele. Argh! Está muito calor aqui, mas calma.. eu deveria sentir essas coisas que humanos sentem? Como imaginei, estou num deserto.E esta garrafa em minha frente têm uma carta..(pegando a carta e abrindo-a) 'Venha de encontro a mim, minha criação mais ilustre. Entretanto o caminho não é tão simples, e testes serão feitos para determinar sua força. À sua esquerda encontrará um caminho que o leva a cidade mais próxima onde encontrará descanso deste sol fastigante,porém esta cidade é estritamente proibida a entrada de robôs. À sua direita, um caminho mais longo porém conhecido por ser lugar de richas entre robôs: cuidado para não ser um alvo. Qual caminho irá escolher? Em seu bolso irá encontrar uma capa de invisibilidade e uma pistola molecular, algo pode te ajudar, ou sua ruina se tornar.'</p></div></div> <button class=neon-bt onclick='carregarConteudo(conteudoB1)'><span></span><span></span><span></span><span></span>Cidade anti-robõs</button> <button class=neon-bt onclick='carregarConteudo(conteudoB2)'><span></span><span></span><span></span><span></span>Cidade das richas</button>";

var conteudoB1 = "<div class=center><div class=page><h2>Conteudo B1</h2>  <p>Decidi ir à cidade anti-robôs e coloquei a capa de invisibilidade para passar ileso pelos cidadões. Poderia soar como uma escolha suicida, mas de certa forma faria com que eu conhecesse mais sobre minhra raça e o porquê do ódio desses humanos pelas máquinas. Após uns 30 minutos de caminhada, me deparei com um enorme portão com os dizeres: Bem-vindo à Moxer City, e mais abaixo uma placa bem explicativa: Robõs não são aceitos aqui. Entrei na cidade por meio da invisibilidade e agradeci mentalmente ao meu criador pelas invenções tão incríveis. Ao meu redor havia diversas pessoas protestando contra uma pessoa chamada Peter Graviscky, em que logo entendi ser a pessoa responsável por eu estar respirando, ou melhor dizendo, por minhas engrenagens estarem em funcionamento. Fui me desviando do turbilhão de pessoas para que um ser invisível não as tocassem de repente, mas uma voz surgiu do nada, uma voz feminina dizendo: 'Olha só! um robô.Melhor ficar quieto e ir andando.' Fiquei atônito quando senti uma arma apontada em minhas costas robotizadas. Desesperado, tinha duas opções: ir para onde quer que ela me levasse ou usar minha arma como forma de defesa.</p> </div></div><button class=neon-bt onclick='carregarConteudo(conteudoC1)'><span></span><span></span><span></span><span></span>Obedecer</button> <button class=neon-bt onclick='carregarConteudo(conteudoC2)'><span></span><span></span><span></span><span></span>Se rebelar</button>";

var conteudoB2 = "<div class=center><div class=page><h2>Conteudo B3</h2> <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. In et quam gravida, sodales nunc non, egestas urna. Nulla quis feugiat libero, eget sollicitudin erat. Pellentesque vulputate arcu at sapien tristique, non bibendum diam aliquam. Quisque at facilisis neque. Integer pretium, ex et consectetur laoreet, turpis magna feugiat velit, ac efficitur odio tortor sed sem. Donec vel leo maximus nisl convallis ornare sit amet id quam. Donec porta aliquet elementum.</p> <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. In et quam gravida, sodales nunc non, egestas urna. Nulla quis feugiat libero, eget sollicitudin erat. Pellentesque vulputate arcu at sapien tristique, non bibendum diam aliquam. Quisque at facilisis neque. Integer pretium, ex et consectetur laoreet, turpis magna feugiat velit, ac efficitur odio tortor sed sem. Donec vel leo maximus nisl convallis ornare sit amet id quam. Donec porta aliquet elementum.</p> </div></div><button class=neon-bt onclick='carregarConteudo(conteudoC3)'><span></span><span></span><span></span><span></span>Ir para a Esquerda</button> <button class=neon-bt onclick='carregarConteudo(conteudoC4)'><span></span><span></span><span></span><span></span>Ir para a Direita</button>";

var conteudoC1 = "<div class=center><div class=page><h2>Conteudo B1</h2>  <p>Para não colocar minha vida em risco, decidi seguir suas ordens. O mais intrigante é que ela não tirou minha capa e mostrou minha identidade ao mundo, era como se apenas estivesse com uma arma apontada para o nada. Pensei muitas vezes em simplesmente correr mas queria saber para onde ela estava me levando e como que conseguiu me ver. Talvez possuia alguma tecnologia avançada. Andamos 5 minutos de puro silêncio e passamos por vários cidadões que a cumprimentavam e um deles a chamou de Kayleh. Ela os cumprimentava de volta com um sorriso de desconfiança e um olhar de preocupação. Era não era uma mercenária, disso eu tenho certeza. Após passar por boa parte da cidade, entramos numa casa longe do centro em que tinham 2 pessoas no que parecia ser uma sala de estar e ao mesmo tempo uma área cheia de ferramentas e bastante pó.'E aí Kayleh, encomenda nova?' - Disse o homem de longos cabelos loiros, pele branca e estatura média, que limpava alguma engrenagem numa força equivalente aos seus músculos dos braços. E essa é das boas - respondeu ela enquanto via a outra pessoa na sala em risos. Fiquei tão assustado que nenhuma palavra saiu de minha boca mecanizada,queria ver o porão onde ela estava me levando. Ao descermos ela tirou minha capa que já não era mais necessária e ligou as luzes do local, revelando no mínimo uma dúzia de robôs de diferentes tipos. 'Bem vindo ao campo de proteção robótica! O nome pode ser meio tosco mas é o que tem protegido a sua raça'. Ela se apresentou para mim, Kayleh Richards, uma garota de 20 anos, morena, cabelo curto e que mostrava um senso de confiança na fala e sua proposta de salvar os robôs que eram sua esperança para mudar o caos da humanidade atual. Quando fui contar sobre minha missão, houve longos disparos por entre a cidade. 'Eu tenho que ir, muito provavelmente chegaram novos robôs por aqui, vou tentar salvar alguns'- disse ela. Me vi numa difícil escolha, seguir ela para salvar mais robôs ou buscar entender mais sobre minha raça em meio a conversa com as outras máquinas do porão.</p></div></div><button class=neon-bt onclick='carregarConteudo(conteudoD1)'><span></span><span></span><span></span><span></span>Ir junto a Kayleh</button> <button class=neon-bt onclick='carregarConteudo(conteudoD2)'><span></span><span></span><span></span><span></span>Juntar-se aos robôs no porão</button>";

var conteudoC2 = "<div class=center><div class=page><h2>Conteudo B3</h2> <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. In et quam gravida, sodales nunc non, egestas urna. Nulla quis feugiat libero, eget sollicitudin erat. Pellentesque vulputate arcu at sapien tristique, non bibendum diam aliquam. Quisque at facilisis neque. Integer pretium, ex et consectetur laoreet, turpis magna feugiat velit, ac efficitur odio tortor sed sem. Donec vel leo maximus nisl convallis ornare sit amet id quam. Donec porta aliquet elementum.</p> <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. In et quam gravida, sodales nunc non, egestas urna. Nulla quis feugiat libero, eget sollicitudin erat. Pellentesque vulputate arcu at sapien tristique, non bibendum diam aliquam. Quisque at facilisis neque. Integer pretium, ex et consectetur laoreet, turpis magna feugiat velit, ac efficitur odio tortor sed sem. Donec vel leo maximus nisl convallis ornare sit amet id quam. Donec porta aliquet elementum.</p> </div></div><button class=neon-bt onclick='carregarConteudo(conteudoC3)'><span></span><span></span><span></span><span></span>Ir para a Esquerda</button> <button class=neon-bt onclick='carregarConteudo(conteudoC4)'><span></span><span></span><span></span><span></span>Ir para a Direita</button>";

var conteudoD1 = "<div class=center><div class=page><h2>Conteudo B1</h2>  <p>Precisava de respostas tanto quanto precisava salvar as máquinas. Queria entender mais sobre Kayleh e a segui sem hesitar. Sem a capa e somente com minha pistola em mãos, entrei na luta para defender meu povo junto de Kayleh. Atiramos em alguns cidadões para imobilizá-los e corremos entre atalhos para chegar rapidamente ao encontro dos robôs. AO chegarmos no meio do campo de batalha, haviam muitos feridos tanto dos robôs quanto dos humanos. As máquinas tinham habilidades mais avançadas do que as minhas e percebi um símbolo na cabeça deles escrito 'DarkNet', seria algum tipo de organização secreta? Avisei a Kayleh que ao ver ficou assustada e disse: Corre para o porão já! Fui imediamente ao sentido da casa robótica que apelidei mas os olhares dos robôs vieram em minha direção. Atirarem em minha perna e raptaram em questaão de segundos. Olhei Kayleh que correu ao meu encontro mas foi parada pelo homem loiro da casa robótica que descobri um pouco antes que seu nome era Alex. Apenas vi os dois voltando para a casa e eu sendo levado muito longe daquele local. Desligaram minha bateria e quando ligaram novamente eu estava em um laboratório, preso em uma cadeira ao redor de vários robôs da tal DarkNet e um cientista maluco que não parava de mexer nas engrenagens do meu corpo. 'Olha só quem acordou' - disse o cientista de cabelos brancos, que tinha um corpo robusto e de grande altura. Quem é você? - perguntei com a voz entrecortada possivelmente por ele estar mexendo no sistema do meu corpo. 'sou o Doutor Dickson, e quero estudar seu software para usá-lo em minha linha de combate, você será muito útil. Logo após, ele recebeu uma chamada através de seu dispositivo móvel para ir a uma reunião de um tal Senhor Cribbs e me deixou aos olhares de 3 robôs armados com um fuzil cada, dando-me apenas a liberdade de ficar solto na sala, pois por mexer em minhas engrenagens eu não teria forças suficientes para me locomover. Ao meu lado tinha uma faca e do outro lado da sala a pistola. Precisava chegar em um deles, qual seria a melhor escolha? </p></div></div><button class=neon-bt onclick='carregarConteudo(conteudoC1)'><span></span><span></span><span></span><span></span>Pegar a faca</button> <button class=neon-bt onclick='carregarConteudo(conteudoC2)'><span></span><span></span><span></span><span></span>Correr em busca da pistola</button>";

var conteudoD2 = "<div class=center><div class=page><h2>Conteudo B3</h2> <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. In et quam gravida, sodales nunc non, egestas urna. Nulla quis feugiat libero, eget sollicitudin erat. Pellentesque vulputate arcu at sapien tristique, non bibendum diam aliquam. Quisque at facilisis neque. Integer pretium, ex et consectetur laoreet, turpis magna feugiat velit, ac efficitur odio tortor sed sem. Donec vel leo maximus nisl convallis ornare sit amet id quam. Donec porta aliquet elementum.</p> <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. In et quam gravida, sodales nunc non, egestas urna. Nulla quis feugiat libero, eget sollicitudin erat. Pellentesque vulputate arcu at sapien tristique, non bibendum diam aliquam. Quisque at facilisis neque. Integer pretium, ex et consectetur laoreet, turpis magna feugiat velit, ac efficitur odio tortor sed sem. Donec vel leo maximus nisl convallis ornare sit amet id quam. Donec porta aliquet elementum.</p></div></div><button class=neon-bt onclick='carregarConteudo(conteudoC3)'><span></span><span></span><span></span><span></span>Ir para a Esquerda</button> <button class=neon-bt onclick='carregarConteudo(conteudoC4)'><span></span><span></span><span></span><span></span>Ir para a Direita</button>";


var elemento = document.getElementById("conteudo");

function carregarConteudo(conteudo){
    elemento.innerHTML = conteudo;
}

function mudarEstilos()  {
    //Dentro dessa função, escreva o codigo para alterar o estilo do elemento com o id "text". 
    //A cor do texto deve ser verde, o tamanho do texto deve ser 15px e a fonte escolhida deve ser Arial;
    //Escreva sua resposta no espaço abaixo.  
    //Um exemplo de alteração de estilos por javascript: text.style.fontFamily = "Comic Sans MS";
    // font-family: banana;
    
    text.style.fontFamily = "Comic Sans MS";
    text.style.color = "white";
    text.style.padding = "20";
    text.style.backgroundColor = "#333";

}

carregarConteudo(conteudoA)